### ISSUE TITLE
Change transition animation?

### ISSUE THREAD

**Issue by Scott1803** [BrunoScheufler/Stapel#6]
First of all, thank you for the amazing work, I have been using this package in my application, and it works great!

My only question is, can I change the animation with which new pages animate in and out?

**Comment by BrunoScheufler** [comment]
Sorry for the late response, perhaps adding transitions to the view that is rendered by the (root) pusher could work here? I'm not sure if you need to modify the parent view for animation purposes, but let me know if you think that's the case. Otherwise, I think animations/transitions should already work 🤔
